#pragma once


#include <vector>

typedef std::vector<char> Buffer;

enum MessageType : char
{
    LOG_IN_REQUEST = 10,
    LOG_IN_RESPONSE = 50,
    SIGN_UP_REQUEST = 11,
    SIGN_UP_RESPONSE = 51,
    LOG_OUT_REQUEST = 17 ,
    LOG_OUT_RESPONSE = 57,
    JOIN_ROOM_REQUEST = 12, 
    JOIN_ROOM_RESPONSE = 52,
    CREATE_ROOM_REQUEST = 13, 
    CREATE_ROOM_RESPONSE = 53,
    GET_PLAYERS_REQUEST = 14,
    GET_PLAYERS_RESPONSE = 54,
    GET_PERSONAL_STATS_REQUEST = 15,
    GET_PERSONAL_STATS_RESPONSE = 55,
    GET_ROOMS_REQUEST = 16,
    GET_ROOMS_RESPONSE = 56,
    GET_HIGH_SCORES_REQUEST = 18,
    GET_HIGH_SCORES_RESPONSE = 58,
    CLOSE_ROOM_REQUEST = 19,
    CLOSE_ROOM_RESPONSE = 59,
    START_GAME_REQUEST = 20 ,
    START_GAME_RESPONSE = 60 ,
    LEAVE_ROOM_REQUEST = 21 ,
    LEAVE_ROOM_RESPONSE = 61,
    ROOM_STATE_REQUEST = 22 ,
    ROOM_STATE_RESPONSE = 62 ,
    ERROR_RESPONSE = 99,
};




